### ISSUE TITLE
Adguard UI won´t start after last upgrade to  v0.108.0-b.48-dark

### ISSUE THREAD

**Issue by buzztee** [iganeshk/adwireguard-dark#7]
Container was upgraded via Watchtower to the Latest release, after the upgrade the Adguard UI won´t stark properly.
Here are the container logs
```
Running AdGuardHome in background
Running wg-easy in background
2023/11/10 14:00:18.158144 [info] AdGuard Home, version v0.108.0-b.48-dark
2023/11/10 14:00:18.159937 [info] tls: using default ciphers
2023/11/10 14:00:18.161199 [info] safesearch default: disabled
2023/11/10 14:00:18.167163 [info] Initializing auth module: /opt/adwireguard/work/data/sessions.db
2023/11/10 14:00:18.167936 [info] auth: initialized.  users:1  sessions:0
2023/11/10 14:00:18.168197 [info] AdGuard Home updates are disabled
2023/11/10 14:00:18.168406 [info] web: initializing
2023/11/10 14:00:18.213839 [info] dnsproxy: cache: enabled, size 4096 b
2023/11/10 14:00:18.214223 [info] dnsproxy: max goroutines is set to 300
2023/11/10 14:00:18.215826 [info] AdGuard Home is available at the following addresses:
2023/11/10 14:00:18.216219 [info] go to http://127.0.0.1:3000
2023/11/10 14:00:18.216399 [info] go to http://10.10.10.2:3000
2023/11/10 14:00:18.216079 [info] clients: processing addresses
/opt/adwireguard/lib/Server.js:138
      .listen(PORT, WEBUI_HOST, () => {
                    ^
ReferenceError: WEBUI_HOST is not defined
    at new Server (/opt/adwireguard/lib/Server.js:138:21)
    at Object.<anonymous> (/opt/adwireguard/services/Server.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/opt/adwireguard/server.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
Node.js v18.18.2
```
The docker-compose used is:
```
version: "3.8"
services:
  adwireguard:
    container_name: adwireguard
    # image: ghcr.io/iganeshk/adwireguard-dark:latest
    image: iganesh/adwireguard-dark:latest
    restart: unless-stopped
    ports:
      - '53:53'           # AdGuardHome DNS Port
      - '3003:3000'       # Default Address AdGuardHome WebUI
      - '853:853'         # DNS-TLS
      - '51820:51820/udp' # wiregaurd port
      - '51821:51821/tcp' # wg-easy webUI
    environment:
        # WG-EASY ENVS
      - WG_HOST=<removed>
      - PASSWORD=<removed>
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.11.x
      - WG_DEFAULT_DNS=10.10.10.2
      - WG_MTU=1420
    volumes:
        # adguard-home volume
      - '~/docker/adguard/work:/opt/adwireguard/work'
      - '~/docker/adguard/conf:/opt/adwireguard/conf'
        # wg-easy volume
      - '~/docker/wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1    # Disable IPv6
    networks:
      vpn_net:
        ipv4_address: 10.10.10.2

networks:
  vpn_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
```

**Comment by gyaneesh** [comment]
@buzztee nice catch! This occurred when I was trying to slipstream bunch of dependency updates and feature additions. One of them was https://github.com/wg-easy/wg-easy/pull/395 and patch generated had an issue.

I have fixed this and re-uploaded/republished binaries/images. Try again and let me know :)

__edit__

WEBUI_HOST env variable is now introduced to prevent wg-easy from naturally binding to `0.0.0.0`

**Comment by buzztee** [comment]
That fixed it, thank you!
